name: fmt

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  fmt-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup git
        run: echo ${{ github.head_ref || github.ref_name }}

      - name: List current directory structure
        run: ls -R /home/runner/work/house-of-fun/house-of-fun

      - name: Create a change
        run: |
          mkdir -p code
          touch code/test1.txt
          git add code/test1.txt

      - uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "🤖 fmt"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
